- packages/sdk/src/constants.ts
- packages/sdk/src/index.ts
> chore: update sdk to use prod SDK url

- README.md
- packages/sdk/src/index.ts
Defines new SDK interface to allow for DOM element injection and new swap and buy apis.
> feat: Improve embedded SDK interface

- .changeset/tiny-cats-sip.md
- README.md
- packages/sdk/README.md
- packages/sdk/src/index.ts
> feat: add namespace

- .changeset/shiny-hats-fry.md
- packages/sdk/src/index.ts
Add timestamp to avoid cached sdk
> feat: Timestamp

- .changeset/famous-numbers-film.md
- README.md
- VERSIONING.md
- packages/sdk/README.md
- packages/sdk/src/index.ts
This pull request includes updates to the documentation and the README file, as well as a new versioning guide. The most important changes include updating the documentation to expose new interfaces, simplifying the README file, and moving the versioning and publishing instructions to a new file.
Documentation Updates:
* [`.changeset/famous-numbers-film.md`](diffhunk://#diff-4296c89ecc575c85832f0b7fea4a827659abff665bf4b8c7993e022e2147e63bR1-R5): Updated documentation and exposed `phantom.ethereum` and `phantom.solana` interfaces.
README Simplification:
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L1-L146): Simplified the README content by removing detailed configuration and usage instructions, and provided a basic overview and …
> docs: Update SDK documentation

- package.json
- packages/browser-sdk/package.json
- packages/browser-sdk/src/solana/getProvider.ts
- packages/browser-sdk/src/solana/plugin.ts
- packages/browser-sdk/src/solana/signAllTransactions.test.ts
- packages/browser-sdk/src/solana/signAllTransactions.ts
- packages/browser-sdk/src/solana/signAndSendTransaction.test.ts
- packages/browser-sdk/src/solana/signAndSendTransaction.ts
- packages/browser-sdk/src/solana/signIn.test.ts
- packages/browser-sdk/src/solana/signIn.ts
- packages/browser-sdk/src/solana/signMessage.test.ts
- packages/browser-sdk/src/solana/signMessage.ts
- packages/browser-sdk/src/solana/signTransaction.test.ts
- packages/browser-sdk/src/solana/signTransaction.ts
- packages/browser-sdk/src/solana/types.ts
- packages/browser-sdk/tsconfig.json
- tsconfig.json
- yarn.lock
Implements signMessage, signTransaction, signAndSendTranscation, signIn, signAllTransactions, and tests
> feat: Sign transaction and messages for solana browser methods

- packages/browser-sdk/src/solana/adapters/deeplinks.ts
- packages/browser-sdk/src/solana/adapters/kms.ts
- packages/browser-sdk/src/solana/getAdapter.ts
Add mock KMS and deeplink adapters
> feat: Mock kms and deeplinks adapter

- .changeset/good-mugs-stare.md
> release: v0.0.7

- packages/server-sdk/INTEGRATION.md
- packages/server-sdk/README.md
- packages/server-sdk/src/constants.ts
- packages/server-sdk/src/index.ts
- packages/server-sdk/src/types.ts
- packages/server-sdk/tests/caip2-mappings.test.ts
- packages/server-sdk/tests/server-sdk.test.ts
Adds the getWallets method for organizations.
Fixes the signmessage method
Makes readme more dev friendly
> chore: Add getWallets, update readme

- packages/browser-sdk/README.md
- packages/browser-sdk/package.json
- packages/browser-sdk/src/extension/index.ts
- packages/browser-sdk/src/extension/isInstalled.ts
- packages/browser-sdk/src/extension/plugin.ts
- packages/browser-sdk/src/index.ts
- packages/react-sdk/README.md
- packages/react-sdk/package.json
- packages/react-sdk/src/extension/index.ts
- packages/react-sdk/src/extension/useIsInstalled.ts
- packages/react-sdk/src/solana/useAccountEffect.test.tsx
- Introduces a new `extension` plugin for extension capabilities
- Add a method to detect whether the phantom extension is installed
> feat: Add method to detect whether extension is installed

- .changeset/weak-poems-tickle.md
- README.md
- examples/browser-sdk-demo-app/src/main.ts
- examples/react-sdk-demo-app/src/Actions.tsx
- examples/server-sdk-examples/src/server-sdk-demo.ts
- examples/server-sdk-examples/src/sign-message.ts
- packages/api-key-stamper/package.json
- packages/base64url/package.json
- packages/browser-sdk/README.md
- packages/browser-sdk/package.json
- packages/browser-sdk/src/BrowserSDK.test.ts
- packages/browser-sdk/src/BrowserSDK.ts
- packages/browser-sdk/src/ProviderManager.ts
- packages/client/README.md
- packages/client/package.json
- packages/client/src/PhantomClient.ts
- packages/client/src/types.ts
- packages/crypto/package.json
- packages/react-sdk/README.md
- packages/react-sdk/src/hooks/useSignMessage.ts
- packages/react-ui/README.md
- packages/react-ui/package.json
- packages/react-ui/src/PhantomUIProvider.tsx
- packages/react-ui/src/hooks/useSignMessage.ts
- packages/server-sdk/README.md
- packages/server-sdk/package.json
- packages/server-sdk/src/index.ts
- packages/server-sdk/tests/server-sdk.test.ts
Fix interfaces so all the public methods have an object as parameter, try to fix release process
> feat: new interface and fix release process

- examples/react-sdk-demo-app/.env.example
- examples/react-sdk-demo-app/package.json
- examples/react-sdk-demo-app/src/Actions.css
- examples/react-sdk-demo-app/src/Actions.tsx
- examples/react-sdk-demo-app/src/App.tsx
- examples/react-sdk-demo-app/src/AuthCallback.css
- examples/react-sdk-demo-app/src/AuthCallback.tsx
- examples/react-sdk-demo-app/src/main.tsx
- packages/react-sdk/src/PhantomProvider.tsx
- packages/react-sdk/src/hooks/useConnect.ts
- packages/react-sdk/src/hooks/useDisconnect.ts
- yarn.lock
> fix: React sdk

- .changeset/nasty-phones-beam.md
- examples/browser-sdk-demo-app/src/main.ts
- examples/react-native-sdk-demo-app/app/_layout.tsx
- examples/react-sdk-demo-app/src/Actions.tsx
- examples/react-sdk-demo-app/src/App.tsx
- examples/react-sdk-demo-app/src/AuthCallback.tsx
- examples/react-sdk-demo-app/src/components/DebugConsole.tsx
- examples/react-sdk-demo-app/src/contexts/DebugContext.tsx
- packages/browser-sdk/README.md
- packages/browser-sdk/src/BrowserSDK.ts
- packages/browser-sdk/src/types.ts
- packages/react-native-sdk/README.md
- packages/react-native-sdk/src/PhantomProvider.tsx
- packages/react-native-sdk/src/index.ts
- packages/react-native-sdk/src/types.ts
- packages/react-sdk/README.md
- packages/react-sdk/src/PhantomProvider.tsx
- packages/react-sdk/src/index.ts
Fixes debug system that was causing re-renderings and reinstantiations of sdk
> fix: Debug system

- packages/browser-sdk/src/global.d.ts
- packages/browser-sdk/src/providers/embedded/index.ts
- packages/browser-sdk/src/utils/browser-detection.ts
- packages/browser-sdk/tsup.config.ts
- packages/client/src/PhantomClient.ts
- packages/client/src/types.ts
- packages/constants/src/analytics.ts
- packages/constants/src/index.ts
- packages/embedded-provider-core/src/embedded-provider.ts
- packages/embedded-provider-core/src/interfaces/platform.ts
- packages/react-native-sdk/src/PhantomProvider.tsx
- packages/react-native-sdk/src/global.d.ts
- packages/react-native-sdk/tsup.config.ts
- packages/server-sdk/package.json
- packages/server-sdk/src/index.ts
- packages/server-sdk/tsconfig.json
- packages/server-sdk/tsup.config.ts
Add analytic headers to the requests that we do to wallet-service.
> feat:Analytics headers

- examples/with-wagmi/src/phantom-connector.ts
- packages/browser-sdk/src/BrowserSDK.test.ts
- packages/browser-sdk/src/ProviderManager.ts
- packages/browser-sdk/src/providers/embedded/adapters/auth.ts
- packages/browser-sdk/src/providers/embedded/index.ts
- packages/browser-sdk/src/providers/injected/index.ts
- packages/embedded-provider-core/src/auth-flow.test.ts
- packages/embedded-provider-core/src/auth/jwt-auth.ts
- packages/embedded-provider-core/src/embedded-provider.test.ts
- packages/embedded-provider-core/src/embedded-provider.ts
- packages/embedded-provider-core/src/interfaces/auth.ts
- packages/embedded-provider-core/src/types.ts
- packages/react-native-sdk/README.md
- packages/react-native-sdk/src/PhantomProvider.tsx
- packages/react-native-sdk/src/providers/embedded/auth.ts
- packages/react-native-sdk/src/providers/embedded/stamper.ts
- packages/react-native-sdk/src/types.ts
Remove all the references to org Id in the SDK initializatio
> fix: Clean up organization id in sdk config in favor of appId

- examples/browser-sdk-demo-app/src/App.tsx
- packages/embedded-provider-core/src/chains/SolanaChain.ts
- packages/parsers/src/response-parsers.test.ts
- packages/parsers/src/response-parsers.ts
> fix: parse transaction response

- .changeset/petite-showers-stay.md
- packages/browser-injected-sdk/src/ethereum/plugin.ts
- packages/browser-injected-sdk/src/solana/plugin.ts
- packages/browser-sdk/src/providers/injected/index.test.ts
- packages/browser-sdk/src/providers/injected/index.ts
Detect account changed events in the injected provider
> fix: Hook into provider account changed event

- .changeset/clear-parts-battle.md
- examples/with-nextjs/src/app/layout.tsx
- examples/with-nextjs/src/app/page.tsx
- examples/with-nextjs/src/components/ServerSafeLayout.tsx
- examples/with-nextjs/src/components/WalletInterface.tsx
- packages/react-sdk/src/PhantomProvider.tsx
- packages/react-sdk/src/hooks/useEthereum.ts
- packages/react-sdk/src/hooks/useSolana.ts
Instead of forcing use client on nextjs implementation, have a dynamic SDK instantiation that allows the provider to be added at a root level for better developer experience.
> fix: support SSR

- .changeset/heavy-clowns-taste.md
- examples/client-demo-app/package.json
- packages/react-sdk/src/PhantomProvider.tsx
Cleanup on navigation caused issues
> fix: cleanup

- .changeset/metal-eyes-deny.md
- packages/client/src/PhantomClient.ts
- packages/embedded-provider-core/src/embedded-provider.ts
The parameter expiresInMs was set on the wrong place
> fix: expires in ms
